# The course so far...

* Whirlwind through Python
* Filer, CLI, OO
* Plotting
* Numpy
* Pandas
* Multiprocessing, generators and requests
* Graphs and PageRank
* Webscraping

## What is left ...

* Feature engineering
* Neural networks
* Image processing
* Movement detection

* Project!

# Learning objectives

## Skills 

* Write Python scripts and programs using common language constructs in the read-eval-print-loop (REPL), “Jupyter Notebooks”, as well as separate self-contained programs. 

* Download files from the web programmatically, as well as reading most common file formats programmatically. 

* Create various types of plots programmatically to share insight into data. 

* Apply Python’s scientific libraries and some of the most prominent algorithms in data science for problem solving and complexity reduction. 

* Programmatically, process images and streams of images. 

* Automate repetitive and boring tasks for example for data collection or UI testing. 

 



## Competencies 

* collect various types of data 

* formulate problems about this data 

* implement solutions to given problem statements 

* present results on an abstract as well as technical level 

*  gain experiences in code reviews by reviewing Python code of their fellow students

## Exam
* Group presentation of 10 minutes followed by 10 minutes of questions per student (minimum 30 minutes). 

* The exam is based on a presentation of the student’s group project and it is facilitated by an interactive programming environment. Additionally, this includes a discussion of the project’s solutions with respect to the main topics of the course.
* For the main topics questions will be known to the students in advance. 

## Agenda

* Linear algebra
  * Vector and matrix operations
  * Matrix operations
* Feature engineering 
* Machine learning basics

## Vector operations

Vectors are list of numbers, and you can do a number of things with them!

In [1]:
import numpy as np

In [2]:
scalar = 7

v = np.array([1, 5, 8, -2, 6])

In [3]:
v.shape

(5,)

In [4]:
np.array([[1], [5], [8], [-2], [0]]).shape

(5, 1)

In [5]:
np.array([[1, 3], [0]]).shape

(2,)

In [6]:
v.reshape(-1, 1)

array([[ 1],
       [ 5],
       [ 8],
       [-2],
       [ 6]])

In [7]:
v.reshape(-1, 1)

array([[ 1],
       [ 5],
       [ 8],
       [-2],
       [ 6]])

### Vector - scalar operations

In [8]:
# Addition
v + scalar

array([ 8, 12, 15,  5, 13])

![](images/vector_addition.svg)

In [9]:
# Subtraction
v - scalar

array([-6, -2,  1, -9, -1])

In [10]:
# Division
v / scalar

array([ 0.14285714,  0.71428571,  1.14285714, -0.28571429,  0.85714286])

In [11]:
# Multiplication
v * scalar

array([  7,  35,  56, -14,  42])

### Vector - vector operations

In [12]:
v = np.array([1, 5, 8, -2, 6])
p = np.array([2, 0, -1])

In [13]:
v + v

array([ 2, 10, 16, -4, 12])

In [14]:
v + p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [15]:
v - v

array([0, 0, 0, 0, 0])

In [16]:
v - p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [17]:
v / v

array([1., 1., 1., 1., 1.])

In [18]:
v / p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [19]:
v * p

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
v / p

## Matrix operations

Math: $v = \begin{bmatrix} -2 & 0 & 1 \\ 5 & -4 & 2 \\ 7 & -1 & 3\end{bmatrix}$

Python:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
```

In [21]:
scalar = 7
p = np.array([2, 0, -1])

m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])

In [22]:
m.shape

(3, 3)

In [ ]:
m.shape

### Matrix - scalar operations

In [23]:
m + scalar # Addition

array([[ 5,  7,  8],
       [12,  3,  9],
       [14,  6, 10]])

In [24]:
m - scalar # Subtraction

array([[ -9,  -7,  -6],
       [ -2, -11,  -5],
       [  0,  -8,  -4]])

In [25]:
m / scalar # Division

array([[-0.28571429,  0.        ,  0.14285714],
       [ 0.71428571, -0.57142857,  0.28571429],
       [ 1.        , -0.14285714,  0.42857143]])

In [26]:
m * scalar # Multiplication

array([[-14,   0,   7],
       [ 35, -28,  14],
       [ 49,  -7,  21]])

### Matrix - vector operations

In [27]:
print("Matrix: \n", m)
print("Vector: ", p)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  0 -1]


In [28]:
m + p

array([[ 0,  0,  0],
       [ 7, -4,  1],
       [ 9, -1,  2]])

In [29]:
m - p

array([[-4,  0,  2],
       [ 3, -4,  3],
       [ 5, -1,  4]])

In [30]:
print("Matrix: \n", m)
print("Vector: ", p)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  0 -1]


In [31]:
m / p

/home/jens/.virtualenvs/slides/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/jens/.virtualenvs/slides/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[-1. ,  nan, -1. ],
       [ 2.5, -inf, -2. ],
       [ 3.5, -inf, -3. ]])

In [32]:
m * p # Note, this is NOT called matrix multiplication!!!

array([[-4,  0, -1],
       [10,  0, -2],
       [14,  0, -3]])

In [33]:
print("Matrix: \n", m)
print("Vector: ", v)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 1  5  8 -2  6]


In [34]:
m + v

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [35]:
m - v

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [36]:
m / v

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [37]:
m * v

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

### Matrix - matrix operations

In [38]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])

In [39]:
m.shape

(3, 3)

In [40]:
m + m

array([[-4,  0,  2],
       [10, -8,  4],
       [14, -2,  6]])

In [41]:
m - m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
m / m

/home/jens/.virtualenvs/slides/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., nan,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [43]:
m * m # Note, this is NOT matrix multiplication

array([[ 4,  0,  1],
       [25, 16,  4],
       [49,  1,  9]])

### Entry-wise product, Hadamard product

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hadamard_product_qtl1.svg/220px-Hadamard_product_qtl1.svg.png)

In [45]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])

In [48]:
q[0]

array([0, 7])

In [46]:
q.shape

(3, 2)

In [49]:
m + q

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [50]:
m * q

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [ ]:
np.matmul(m, q)

### Matrix multiplication

![](images/matmul.png)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/313px-Matrix_multiplication_diagram_2.svg.png)

### Matrix multiplication exercise

Multiply the following matrix `m × q` by hand:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])
```

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/313px-Matrix_multiplication_diagram_2.svg.png)

In [61]:
m.dot(q).shape

(3, 2)

In [67]:
q.T.shape

(2, 3)

## Matrix transpose

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Matrix_transpose.gif/200px-Matrix_transpose.gif)

In [80]:
a = np.array([[-2, 5], [0, 4]])
b = np.array([0, 7])

35

In [ ]:
np.arange(12).reshape(3, 4).T

In [81]:
m.T

array([[-2,  5,  7],
       [ 0, -4, -1],
       [ 1,  2,  3]])

In [82]:
q = np.array([[0, 7], [-3, 2], [1, 5]])

In [84]:
q.shape

(3, 2)

In [85]:
q.T.shape

(2, 3)